### ISSUE TITLE
week 01 回覆

### ISSUE THREAD

**Issue by azole** [kkai0828/git-practice#1]
請補交作業，補交方向如下:

- 你提到「這個雜湊值會被當成blob物件的檔名儲存在.git資料夾中」，那存在 .git 檔案夾中的哪裡？怎麼存呢？
- 「branch就是把某個commit複製一個版本出來」-> 這句話應該不太正確，請找出正確的說明
- 記錄.git的變化: 你列出來的第一次 commit 跟 第二次 commit 變化在哪裡？為什麼會有這些變化？

試著把作業做得更深入一點，訓練自己有好奇心與提問的能力，幫助自己有更深層思考的能力。

補交期限: 9/21 六 23:00 前

**Comment by KaifeinDev** [comment]
* 會儲存.git/objects中的，計算的SHA-1值首兩位會變成資料夾名稱，剩餘的部分會變成該資料夾中的檔案名稱，而Blob的二進位資訊儲存在該檔案中。
* 根據網路上的資料，「複製」這個詞的確不太正確，branch應該是指向特定commit的指標。
* (0919)待更新...

**Comment by KaifeinDev** [comment]
0920 update:
1. 補交內容已更新
2. 上傳 week-02 部分

**Comment by azole** [comment]
收到，謝謝你的補交與回覆，之後的作業都要保持這個水準，喔不是，要基於這個起點，讓自己持續進步，好嗎？

week-02 的部分我明天一起看， 如果沒有其他需要跟我討論的事，這個 issue 可以 close 了。

**Comment by KaifeinDev** [comment]
謝謝老師
